name = "csbox"

account_id = "4ccb114e028a029b7a8d337b1e239b1a"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2021-11-12"
workers_dev = true

[placement]
mode = "smart"

[env.production.vars]
PUBLIC_SUPABASE_URL = "https://bpjcaiybudgwujfpyevt.supabase.co"
PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwamNhaXlidWRnd3VqZnB5ZXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzMyODg3NzIsImV4cCI6MTk4ODg2NDc3Mn0.s8MK11TtrcjWiaeOtM5wCWQ9yoVKJP1Uy1w_HIDqVUs"
DEV_MODE = "true"
PRIVATE_ADMIN_MASTER_KEY = "eyJhbGciOiJQUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.J5W09-rNx0pt5_HBiydR-vOluS6oD-RpYNa8PVWwMcBDQSXiw6-EPW8iSsalXPspGj3ouQjAnOP_4-zrlUUlvUIt2T79XyNeiKuooyIFvka3Y5NnGiOUBHWvWcWp4RcQFMBrZkHtJM23sB5D7Wxjx0-HFeNk-Y3UJgeJVhg5NaWXypLkC4y0ADrUBfGAxhvGdRdULZivfvzuVtv6AzW6NRuEE6DM9xpoWX_4here-yvLS2YPiBTZ8xbB3axdM99LhES-n52lVkiX5AWg2JJkEROZzLMpaacA_xlbUz_zbIaOaoqk8gB5oO7kI6sZej3QAdGigQy-hXiRnW_L98d4GQ"
PRIVATE_CLOUDFLARE_SECRET_KEY = "0x4AAAAAAAFpCO-CZguCf38CF3-mvb3TvlA"
PUBLIC_SUPABASE_ID = "bpjcaiybudgwujfpyevt"
PRIVATE_LTI_API_KEY="dbb8213d-725e-4d9c-8636-84aae79f1389"

