name: Deploy to CF Worker

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Node Check
        run: npm run check

      - name: SvelteKit Sync
        run: npx @sveltejs/kit sync

      - name: Build Svelte Kit
        run: npm run build

      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo "Deploying to Cloudflare Worker"
          echo "CF_ACCOUNT_ID=${CF_ACCOUNT_ID}"
          echo "CF_ZONE_ID=${CF_ZONE_ID}"
          echo "CF_API_TOKEN=${CF_API_TOKEN}"
          echo "PRIVATE_LTI_API_KEY=${PRIVATE_LTI_API_KEY}"
          echo "CF_ACCOUNT_ID=${CF_ACCOUNT_ID}" > .env
          echo "CF_ZONE_ID=${CF_ZONE_ID}" >> .env
          echo "CF_API_TOKEN=${CF_API_TOKEN}" >> .env
          echo "PRIVATE_LTI_API_KEY=${PRIVATE_LTI_API_KEY}" >> .env
          cat .env
          npx wrangler build --legacy-peer-deps
          npx wrangler publish
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          PRIVATE_LTI_API_KEY: ${{ secrets.PRIVATE_LTI_API_KEY }}